### ISSUE TITLE
Full Calendar 1.6.4 support

### ISSUE THREAD

**Issue by Karttin** [joshgerdes/jquery.ui.touch#2]
Hello Joshgerdes,

Thanks for the lovely work around.

With simple div tags all seems to work fine for me. When i try to use it with full calendar 1.6.4, it doesn't seems to work.

If possible can you please create a sample plunker / jsfiddle which works with full calendar 1.6.4?

Kind Regards
Kay

**Comment by moisadoru** [comment]
I am using this and it works with FullCalendar 2.3.1:
```javascript
eventAfterRender : function(event, $element, view) {
    $element.addTouch();
}
```

**Comment by joshgerdes** [comment]
Thanks for the testing @moisadoru. We'll call this one closed then.
